/**
 * Server component — renders a species range map as inline SVG.
 *
 * Style modeled on E. L. Little's Atlas of United States Trees:
 *   - off-white land, grey state borders
 *   - solid green range polygon
 *   - subtle New-England highlight so users can orient themselves
 *
 * Data: reads pre-computed GeoJSON from data/ranges/{slug}.json
 * and a shared basemap from data/basemap/na-basemap.json (both
 * generated by scripts/14-range-maps.ts and scripts/build-basemap.ts).
 *
 * If no range file exists for the slug, renders nothing.
 */

import { geoAlbers, geoPath, type GeoProjection } from "d3-geo";
import type { Feature, GeoJsonProperties, Geometry } from "geojson";
import { getBasemap, getRangeForSpecies, type SpeciesRange } from "@/lib/data/ranges";

const WIDTH = 800;
const HEIGHT = 500;

// Framing polygon (counter-clockwise) covering mainland North America.
// Passed to fitExtent so every species map frames the same area — a
// species dot in Vermont sits in the same spot across all 10,000 maps.
const NA_FRAME = {
  type: "Polygon" as const,
  coordinates: [
    [
      [-128, 14],
      [-128, 60],
      [-55, 60],
      [-55, 14],
      [-128, 14],
    ],
  ],
};

function buildProjection(): GeoProjection {
  // Albers equal-area conic with parameters traditional for NA atlases.
  // Standard parallels at 29.5/45.5 are classic for the lower 48.
  return geoAlbers()
    .rotate([96, 0])
    .center([0, 38])
    .parallels([29.5, 45.5])
    .fitExtent(
      [
        [10, 10],
        [WIDTH - 10, HEIGHT - 10],
      ],
      NA_FRAME
    );
}

function sourceLabel(source: SpeciesRange["source"]): string {
  switch (source) {
    case "littles":
      return "Native range — Little (1971) via USGS";
    case "inat-hull":
      return "Observation range — iNaturalist";
  }
}

export default function RangeMap({ slug }: { slug: string }) {
  const range = getRangeForSpecies(slug);
  const basemap = getBasemap();
  if (!range || !basemap) return null;

  const projection = buildProjection();
  const path = geoPath(projection);

  const pathOf = (f: Feature<Geometry, GeoJsonProperties>): string =>
    path(f) ?? "";

  return (
    <figure className="bg-card border border-border rounded-xl overflow-hidden">
      <svg
        viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
        className="w-full h-auto block bg-cream"
        role="img"
        aria-label={`Range map for ${range.scientificName}`}
      >
        {/* Countries — a barely-visible background tint so water reads as white */}
        <g>
          {basemap.countries.features.map((f, i) => (
            <path
              key={`c-${i}`}
              d={pathOf(f)}
              fill="#efece3"
              stroke="none"
            />
          ))}
        </g>

        {/* New England highlight — draw beneath states so state borders still show */}
        <g>
          {basemap.neStates.features.map((f, i) => (
            <path
              key={`ne-${i}`}
              d={pathOf(f)}
              fill="#e3dfd0"
              stroke="none"
            />
          ))}
        </g>

        {/* States / provinces — thin black-ish borders */}
        <g>
          {basemap.states.features.map((f, i) => (
            <path
              key={`s-${i}`}
              d={pathOf(f)}
              fill="none"
              stroke="#9a9382"
              strokeWidth={0.5}
              strokeLinejoin="round"
            />
          ))}
        </g>

        {/* Country outlines — heavier stroke */}
        <g>
          {basemap.countries.features.map((f, i) => (
            <path
              key={`co-${i}`}
              d={pathOf(f)}
              fill="none"
              stroke="#6b6554"
              strokeWidth={0.9}
              strokeLinejoin="round"
            />
          ))}
        </g>

        {/* Range polygon */}
        <path
          d={pathOf(range.polygon)}
          fill="var(--color-forest, #2d6a4f)"
          fillOpacity={0.55}
          stroke="var(--color-forest, #2d6a4f)"
          strokeWidth={1}
          strokeLinejoin="round"
        />
      </svg>

      <figcaption className="px-4 py-2 text-xs font-ui text-text-secondary bg-cream-dark/30 border-t border-border flex items-center justify-between gap-3">
        <span>{sourceLabel(range.source)}</span>
        {range.observationCount !== undefined && (
          <span className="text-text-muted">
            {range.observationCount.toLocaleString()} observations
          </span>
        )}
      </figcaption>
    </figure>
  );
}
